---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certgen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certgen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certgen
subjects:
- kind: ServiceAccount
  name: certgen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certgen
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
---
apiVersion: batch/v1
kind: Job
metadata:
  name: certgen
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        app: "certgen"
    spec:
      containers:
      - name: envoy-gateway-certgen
        image: docker.io/envoyproxy/gateway-dev:0c9d4f6
        imagePullPolicy: IfNotPresent
        command:
        - envoy-gateway
        - certgen
        env:
        - name: ENVOY_GATEWAY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      restartPolicy: Never
      serviceAccountName: certgen
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
  parallelism: 1
  completions: 1
  backoffLimit: 1
