{{- $sa := .Values.serviceAccount | default dict }}
{{- $saCreate := ternary $sa.create true (hasKey $sa "create") }}
{{- if $saCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eg.serviceAccountName" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "eg.labels" . | nindent 4 }}
{{- end }}
