apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoyproxy-sample
spec:
  # TODO(user): Add fields here
  provider:
    type: kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
