apiVersion: v2
name: gateway-addons-helm
description: An Add-ons Helm chart for Envoy Gateway
type: application

version: v0.0.0-latest
appVersion: "latest"
icon: https://raw.githubusercontent.com/envoyproxy/gateway/main/site/assets/icons/logo.svg

maintainers:
  - name: envoy-gateway-steering-committee
    url: https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
  - name: envoy-gateway-maintainers
    url: https://github.com/envoyproxy/gateway/blob/main/CODEOWNERS

keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway
  - eg

home: https://gateway.envoyproxy.io/

sources:
  - https://github.com/envoyproxy/gateway

dependencies:
  - name: prometheus
    version: 27.50.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 10.3.0
    condition: grafana.enabled
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.54.0
    condition: fluent-bit.enabled
  - name: alloy
    repository: https://grafana.github.io/helm-charts
    version: 1.5.0
    condition: alloy.enabled
  - name: loki
    version: 6.46.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: tempo
    repository: https://grafana.github.io/helm-charts
    version: 1.24.1
    condition: tempo.enabled
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.141.0
    condition: opentelemetry-collector.enabled
