apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "eg.labels" . | nindent 4 }}
data:
  envoy-gateway.yaml: |
    apiVersion: config.gateway.envoyproxy.io/v1alpha1
    gateway:
      controllerName: {{ .Values.config.envoyGateway.gateway.controllerName
        | quote }}
    kind: EnvoyGateway
    {{- toYaml .Values.config.envoyGateway | nindent 4 }}
