name: Welcome

on:
  pull_request_target:
    types: [opened]

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ðŸš€ Thank you for contributing to the [Envoy Gateway](https://gateway.envoyproxy.io/) project! ðŸš€

            Before merging, please ensure to follow the process below:

            1. Requesting Reviews:
            - cc @envoyproxy/gateway-reviewers team for an initial review.
            - After the initial review, reviewers should request the @envoyproxy/gateway-maintainers team for further review.
            2. Review Approval:
            - Your PR needs to receive at least two approvals.
            - At least one approval must come from a member of the gateway-maintainers team.

            **NOTE**: Once your PR is under review, ***please do not rebase and force push it***. Otherwise, it will force your reviewers to review the PR from scratch rather than simply look at your latest changes. 

            <details>
            <summary> What's more, you can help expedite the processing of your PR by </summary>
            <br>

            - Ensuring you have self-reviewed your work according to the project's [Contribution Guidelines](https://gateway.envoyproxy.io/latest/contributions/develop).
            - If your PR addresses a specific issue, make sure to mention it in the PR description.
            - Respond promptly if there are any test failures or suggestions for improvements that we comment on.

            </details>
          reactions: 'heart'
